#!/bin/sh
/kaniko/executor \
    --context "${CI_PROJECT_DIR}" \
    --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
    --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" \
    --destination "${CI_REGISTRY_IMAGE}:latest" \
    --insecure
