name: Build & Publish (server + k8s)

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        # uses GITHUB_TOKEN for ghcr (no PAT needed if packages:write is allowed)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/gr-laniakea/${{ github.event.repository.name }}:latest
            ghcr.io/gr-laniakea/${{ github.event.repository.name }}:${{ github.sha }}
